// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.FileImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Backend.Models.ResultAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FileImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstOperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<double>("TimeDeltaSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AverageExecutionTime");

                    b.HasIndex("AverageValue");

                    b.HasIndex("FileImportId")
                        .IsUnique();

                    b.HasIndex("FirstOperationDate");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Backend.Models.ValueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FileImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FileImportId", "ExecutionTime");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Backend.Models.ResultAggregate", b =>
                {
                    b.HasOne("Backend.Models.FileImport", "FileImport")
                        .WithOne("Result")
                        .HasForeignKey("Backend.Models.ResultAggregate", "FileImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileImport");
                });

            modelBuilder.Entity("Backend.Models.ValueEntry", b =>
                {
                    b.HasOne("Backend.Models.FileImport", "FileImport")
                        .WithMany("Values")
                        .HasForeignKey("FileImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileImport");
                });

            modelBuilder.Entity("Backend.Models.FileImport", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
